[package]
name = "own_lisp"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
env_logger = "0.11.3"
log = "0.4.21"
pest = "2.7.10"
pest_derive = "2.7.10"
pretty_env_logger = "0.5.0"
rustyline = "14.0.0"
serde = {version="1.0.203", features=["derive"]}
